### ISSUE TITLE
Migrate from Cloudant Shared Plan to IBM Cloud

### ISSUE THREAD

**Issue by sdaigle2** [sdaigle2/Abacus-mvp#87]
On Mar 31, 2018, cloudant.com shared plan will become inaccessible and deleted from cloudant servers.   IBM is recomending that we migrate from our Cloudant shared plan to a new IBM Cloud account.  I was able to replicate the data in our old database to the new database, but I am having trouble getting our app to communicate with the new database.

### Reference information
- Our old database is a Cloudant Shared plan account located at https://cloudant.com/sign-in/.   You can log in as intelliwheels and the provided password.
- Our new database is an IBM Cloud account.  You can get to it at https://myibm.ibm.com/ and login with sales@intelliwheels.net and the provided password.  Then go to My IBM Dashboard and click  Launch next to IBM cloud.

### Problems I have encountered.
- When I change the environment variables to the new cloudant account, I am able to start the localhost.  When I try to log in on the site (use sdaigle2@gmail.com wheelchair34 for testing) , I receive a message that it is in incorrect username or password.  I am certain that I am using the correct user name and password but the console shows cloudant errors.

### Deliverables
- You will point a local version of the app to the new database.  
- You will fix whatever needs to be fixed to point to this new database.

### Tests to be performed 
- [x] Log in as sdaigle2@gmail.com with password wheelchair34.  Make certain that it successfully logs in.
- [x] Create a new user.
- [x] Log out and Log in as that new user.

Once you have completed these tests, please commit and push your changes and document what environment variables need to be set to make this work.

**Comment by as-sergey-m** [comment]
Hello, @sdaigle2 
I've made fix for the issue. Please check it out [here](https://github.com/sdaigle2/Abacus-mvp/pull/88).
Also, I remember you required to push to _development_ branch, but I couldn't find it at Abacus-mvp
repo, so I've made PR to push to master.
Please specify to which branch should I push to, and I'll fix PR

**Comment by sdaigle2** [comment]
Thank you for working on that.  I will test this tomorrow.

Yes, I use to require to push to development branch, but PR branch is good too.

**Comment by sdaigle2** [comment]
I tested just now and I wasn't able to succeed.  Here is the process I followed:

1. I merged your changes to the master branch
2. I pulled the changes so that my local copy is up to date
3. I set my environment variables to the old database
4. I ran node server.js
5. I logged in as sdaigle2@gmail.com with password: wheelchair34 - Success
6. I changed my environment variables to the new CLOUDANT_USERNAME and CLOUDANT_PASSWORD specified in IBM Cloud console under "Service credentials"
7. I ran node server.js
8. I tried to log in as sdaigle2@gmail.com with password: wheelchair34.  The browser showed "Incorrect log/in password", the console showed this:
![image](https://user-images.githubusercontent.com/9470060/37244912-e7b69234-2455-11e8-991c-db75c99eefcc.png)

I must be doing something wrong.  It's been a while since I've done any software development management.  I've been focusing on other work lately, so I'm a bit out-of-practice on this kind of thing.  Could you please help me understand what I did wrong?

**Comment by sdaigle2** [comment]
I don't fully understand why, but your recent commit 230f52905cff21710b14d7fe0380c6073968a1c4 fixed it for me locally.  I'm testing more and will get back to you

**Comment by as-sergey-m** [comment]
@sdaigle2 Default max number of attempts was 3, I've increased it to 5, as it indicates such limit in errors. I've tried to login locally with your account 30 times and didn't get any errors after last fix.
I'm investigating source of this issue anyway to be sure

**Comment by as-sergey-m** [comment]
@sdaigle2 You're using _Lite_ plan for IBM Cloud. It allows 5 queries per second only. I advise you to consider changing to _Standart_ plan (up to 1000 queries per second)

**Comment by sdaigle2** [comment]
Good idea.  I will do that.  Once I  have accomplished that, I will close this issue.

**Comment by as-sergey-m** [comment]
@sdaigle2 Here's IBM Cloud prices data. Please check it out
https://console.bluemix.net/docs/services/Cloudant/offerings/bluemix.html#ibm-cloud-public

**Comment by sdaigle2** [comment]
This problem looks to be resolved.
