### ISSUE TITLE
Migrate from One AWS S3 account to another

### ISSUE THREAD

**Issue by sdaigle2** [sdaigle2/Abacus-mvp#90]
We need to migrate from an AWS account with username: sales@intelliwheels.net to one with username: per4maxtech@gmail.com.  This is because we sold the data stored here to per4max, but we can't just change the username on the account because Amazon has it connected to other services like FBA which we did not sell to Per4max.  Therefore, we have to create a whole new account.

# Resources Required:
The passwords document provided separately.

# Steps:
1.) Move all the data from AWS account 1 to AWS account 2. - DONE - Scott completed this a few weeks ago.
2.) Make the application pull data from the new AWS account. - NOT COMPLETE

# How I understand the site to work:
Orignally we set up the app to pull all of the wheelchair pictures from an AWS S3 bucket called
`const CHAIR_PICS_S3_BUCKET = 'tinkerwheelchair';`

I have since revised that bucket to a new bucket in the new AWS account.  The new bucket is called:
`const CHAIR_PICS_S3_BUCKET = 'p4x-intelliwheels';` I made this change with commit 25ace77e887e58405208313aa379feb5a29dd20f

When testing the site, you see these pictures as pictures of the wheelchair
![image](https://user-images.githubusercontent.com/9470060/37557270-fe130128-29cf-11e8-8b40-7aa852bb6efb.png)

# Problems Encountered:

**Steps Already Taken:**
1. When I run the code locally with node server.js, I test it by turning off my internet connection and the pictures still load.  I think the local version is set to pull pictures from the local directory.  I don't know how to turn this off.  When it runs on Heroku, it pulls from AWS S3.  I think it has something to do with the routing.
2. I run the online staging version with an incorrect bucket name, and incorrect AWS credentials in the environment variables, and then it still gets the pictures.  

It seams clear that I don't fully understand how the app is getting those pictures.  So the first step is to  figure that out.  I remember a developer years ago setting up something to pull those pictures from other servers, but I don't know enough about the code to backtrack that.

**Comment by as-sergey-m** [comment]
Hello, @sdaigle2 
Here's PR for this https://github.com/sdaigle2/Abacus-mvp/pull/91 . Please, check it out

**Comment by as-sergey-m** [comment]
Hello, @sdaigle2. Here's explanation of how chairpic retrieval service works:
Basically, it utilizes  least recently used cache to reduce number of requests to S3.
1) When `get()` method is called, it checks if image is stored in local cache first. 
2) If image is in the cache, then path to locally stored image is returned.
3) Otherwise, chairpic retrieval service gets image from S3 and stores it in local cache. 
4) After that the path to newly stored local image is returned.
5) On any error, `emptyImage.png` is retuned

**Comment by sdaigle2** [comment]
Everything seams to be working well.  Closing this issue.
